config/routes.rb
SampleApp::Application.routes.draw do

  match 'booze_user/:id/add' => 'booze_user#add', :as => :booze_user_add
  match 'booze_user/create' => 'booze_user#create', :as => :booze_users
  match 'booze_user/:id/rerate' => 'booze_user#rerate', :as => :booze_user_rerate
  match 'booze_user/update/:id' => 'booze_user#update', :as => :booze_user

  resources :boozes

  devise_for :users

  match '/contact', :to => 'pages#contact'
  match '/about', :to => 'pages#about'
  match '/help', :to => 'pages#help'
  match 'signup', :to => 'users#new'
  root :to => 'pages#home'

end

app/models/booze.rb
class Booze < ActiveRecord::Base
  validates :name, :presence => true
  validates :rating, :inclusion => (1..10)
  has_many :booze_users
  has_many :users, :through => :booze_users

  def get_user_rating(user)
    if booze_users != []
      return booze_users.select{|bu| bu.user == user}[0].user_rating
    end
      "Not Rated"
  end

end

app/models/booze_user.rb
class BoozeUser < ActiveRecord::Base
  belongs_to :booze
  belongs_to :user


  def to_s
    booze.name + " - " + booze.rating.to_s + " - " + user_rating.to_s
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  has_many :booze_users
  has_many :boozes, :through => :booze_users

  def add_booze (booze_to_add, rating)
    bu = BoozeUser.new(:booze => booze_to_add, :user => self)
    bu.user_rating =  rating
    bu.save
  end

  def list_boozes
    booze_users.all.sort!{ |booze1, booze2| booze2.user_rating <=> booze1.user_rating }
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/booze_user_controller.rb
class BoozeUserController < ApplicationController
  #get /boozes/add/1
  def add
    @booze = Booze.find(params[:id])
    @booze_user = BoozeUser.new
    respond_to do |format|
      format.html # add.html.erb
      format.xml  { render :xml => @booze }
    end
  end
  #get /booze/rerate/1
  def rerate
    @booze = Booze.find(params[:id])
    @booze_user = @booze.booze_users.select{|b| b.user == current_user}[0]
  end

  def update
    @booze_user = BoozeUser.find(params[:id])

    respond_to do |format|
      if @booze_user.update_attributes(params[:booze_user])
        format.html { redirect_to(boozes_url, :notice => 'Booze was successfully updated.') }
      else
        format.html { render :action => "rerate" }
      end
    end
  end

  def remove
  end



  # POST /boozes/create
  # POST /boozes/create.xml
  def create
    @booze_user = BoozeUser.new(params[:booze_user])
    @booze_user.user = current_user

    respond_to do |format|
      if @booze_user.save
        @boozes = Booze.all
        format.html { redirect_to boozes_path, :notice => 'Booze #{@booze_user.booze.name} was successfully added to your account.'}
        format.xml  { render :xml => @booze, :status => :created, :location => @booze }
      else
        @booze_users = BoozeUser.all
        format.html { render :action => boozes_path }
        format.xml  { render :xml => @booze_user.errors, :status => :unprocessable_entity }
      end
    end
  end

end

app/controllers/boozes_controller.rb
class BoozesController < ApplicationController
  # GET /boozes
  # GET /boozes.xml
  def index
    @boozes = Booze.all
    @booze = Booze.new
    @current_user = current_user
    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @boozes }
    end
  end

  # GET /boozes/1
  # GET /boozes/1.xml
  def show
    @booze = Booze.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @booze }
    end
  end


  # GET /boozes/new
  # GET /boozes/new.xml
  def new
    @booze = Booze.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @booze }
    end
  end

  # GET /boozes/1/edit
  def edit
    @booze = Booze.find(params[:id])
  end

  # POST /boozes
  # POST /boozes.xml
  def create
    @booze = Booze.new(params[:booze])

    respond_to do |format|
      if @booze.save
        @boozes = Booze.all
        @booze = Booze.new
        format.html { render :action => "index", :notice => 'Booze was successfully created.'}
        format.xml  { render :xml => @booze, :status => :created, :location => @booze }
      else
        @boozes = Booze.all
        format.html { render :action => "index" }
        format.xml  { render :xml => @booze.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /boozes/1
  # PUT /boozes/1.xml
  def update
    @booze = Booze.find(params[:id])

    respond_to do |format|
      if @booze.update_attributes(params[:booze])
        format.html { redirect_to(@booze, :notice => 'Booze was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @booze.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /boozes/1
  # DELETE /boozes/1.xml
  def destroy
    @booze = Booze.find(params[:id])
    @booze.destroy

    respond_to do |format|
      format.html { redirect_to(boozes_url) }
      format.xml  { head :ok }
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def home
    @title = "Home"
  end

  def contact
    @title = "Contact"
  end

  def about
    @title = "About"
  end

  def help
    @title = "Help"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  # Return a title on a per-page basis.
  def title
    base_title = "Boozehound 1.0"
    if @title.nil?
      base_title
    else
      "#{base_title} | #{@title}"
    end
  end

  def logo
    image_tag("logo.jpg", :alt => "Boozehound", :class => "round")
  end
end

app/helpers/booze_user_helper.rb
module BoozeUserHelper
end

app/helpers/boozes_helper.rb
module BoozesHelper
  def render_user_link (booze, user)
    if (booze.get_user_rating(user).to_s.eql?("Not Rated"))
      return link_to 'Add to My Boozes', booze_user_add_path (booze.id)
    end
    link_to 'Change My Rating',booze_user_rerate_path(booze.id)
  end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/booze_user/_form.html.erb
<p>
  <b>Name:</b>
  <%= @booze.name %>
</p>

<p>
  <b>General Rating:</b>
  <%= @booze.rating %>
</p>
<%= form_for(@booze_user) do |f| %>
  <% @booze_user.booze = @booze %>
    <%= f.hidden_field(:booze_id,  :value => @booze.id) %>
  <div class="field">
    <%= f.label :user_rating %><br />
    <%= f.text_field :user_rating %>
  </div>
  <div class="actions">
    <%= f.submit "Update My Rating" %>
  </div>
<% end %>

app/views/booze_user/add.html.erb
<h1>Add this booze</h1>
<%= render 'form' %>

app/views/booze_user/rerate.html.erb
<h1>Re-Rate this booze</h1>
<%= render 'form' %>

app/views/boozes/_form.html.erb
<%= form_for(@booze) do |f| %>
  <% if @booze.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@booze.errors.count, "error") %> prohibited this booze from being saved:</h2>

      <ul>
      <% @booze.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :rating %><br />
    <%= f.text_field :rating %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/boozes/add.html.erb
<h1>Add this booze</h1>
<p>
  <b>Name:</b>
  <%= @booze.name %>
</p>

<p>
  <b>General Rating:</b>
  <%= @booze.rating %>
</p>

app/views/boozes/edit.html.erb
<h1>Editing booze</h1>

<%= render 'form' %>

<%= link_to 'Show', @booze %> |
<%= link_to 'Back', boozes_path %>

app/views/boozes/index.html.erb
<h1>Boozes</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Rating</th>
    <th>Your Rating</th>
    <th></th>
    <th></th>
  </tr>

<% @boozes.each do |booze| %>
  <tr>
    <td><%= booze.name %></td>
    <td><%= booze.rating %></td>
    <td><%= booze.get_user_rating(@current_user) %></td>
    <td><%= link_to 'Edit Booze Info', edit_booze_path(booze) %></td>
    <td><%= link_to 'Delete', booze, :confirm => 'Are you sure?', :method => :delete %></td>
    <td><%= render_user_link(booze, @current_user) %> </td>
  </tr>
<% end %>
</table>

<br />

<%= render 'form' %>

app/views/boozes/new.html.erb
<h1>New booze</h1>

<%= render 'form' %>

<%= link_to 'Back', boozes_path %>

app/views/boozes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @booze.name %>
</p>

<p>
  <b>Rating:</b>
  <%= @booze.rating %>
</p>


<%= link_to 'Edit', edit_booze_path(@booze) %> |
<%= link_to 'Back', boozes_path %>

app/views/layouts/_footer.html.erb
<footer>
  <nav class="round">
    <ul>
      <li><%= link_to "About", about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
      <li><a href="http://news.railstutorial.org/">News</a></li>
      <li><a href="http://www.railstutorial.org/">Rails Tutorial</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header>
  <%= link_to logo, root_path %>
  <nav class="round">
    <ul>
      <li><%= link_to "Home", root_path %></li>
      <li><%= link_to "Help", help_path %></li>

      <li><%= link_to "Sign in", user_session_path if current_user.nil?%></li>
      <li><%= link_to "Sign out", destroy_user_session_path if !current_user.nil?%></li>

    </ul>
  </nav>
</header>

app/views/layouts/_stylesheets.html.erb
<!--[if lt IE 9]>
<script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->
<%= stylesheet_link_tag 'blueprint/screen', :media => 'screen' %>
<%= stylesheet_link_tag 'blueprint/print',  :media => 'print' %>
<!--[if lt IE 8]><%= stylesheet_link_tag 'blueprint/ie' %><![endif]-->
<%= stylesheet_link_tag 'custom', :media => 'screen' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= title %></title>
    <%= csrf_meta_tag %>
    <%= render 'layouts/stylesheets' %>
  </head>
  <body>
    <div class="container">
      <%= render 'layouts/header' %>
      <section class="round">
        <% flash.each do |key, value| %>
          <div class="flash <%= key %>"><%= value %></div>
        <% end %>
        <%= yield %>
      </section>
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>

app/views/pages/about.html.erb
<h1>Pages#about</h1>
<p>Find me in app/views/pages/about.html.erb</p>

app/views/pages/contact.html.erb
<h1>Pages#contact</h1>
<p>Find me in app/views/pages/contact.html.erb</p>

app/views/pages/help.html.erb
<h1>Help</h1>
<p>
  Get help on Ruby on Rails Tutorial at the
  <a href="http://railstutorial.org/help">Rails Tutorial help page</a>.
  To get help on this sample app, see the
  <a href="http://railstutorial.org/book">Rails Tutorial book</a>.
</p>

app/views/pages/home.html.erb
<h1>Boozehound</h1>

<p>
  This is the home page for the
  Boozehound application developed by Chris Hein for Olivia Hein.
</p>

<%= link_to "Add some booze!", boozes_path, :class => "signup_button round" %>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@user.errors.count, "error") %>
        prohibited this user from being saved:</h2>
    <p>There were problems with the following fields:</p>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/users/show.html.erb
<table class="profile" summary="Profile information">
  <tr>
    <td class="main">
      <h1>
        <%= gravatar_for @user %>
        <%= @user.name %>
      </h1>
    </td>
    <td class="sidebar round">
      <strong>Name</strong> <%= @user.name %><br />
      <strong>URL</strong>  <%= link_to user_path(@user), @user %>
    </td>
  </tr>
</table>